### ISSUE TITLE
Control and hover over command opens it.

### ISSUE THREAD

**Issue by CalebSerafin** [HakonRydland/Arma3CfgFunctions#1]
Holding just control when mouse pointer over wiki command opens it.

I have tried factory settings, the issue still occurs.
I have tried disabling auto-complete and header hover.
I have uninstalled and re-installed it.

No setting should enable this action. Makes use of ctrl painful.

### Notes

SQF Wiki already provides a key combination to open the wiki with select command.

**Comment by HakonRydland** [comment]
Problem as a result of registering the wiki lookups as definitions, problem resolved with v1.1.6 commit a182292
