### ISSUE TITLE
#include and macro seams not to work that greate

### ISSUE THREAD

**Issue by AndreasBrostrom** [HakonRydland/Arma3CfgFunctions#2]
Script packages using #include and cba standard macros seams not to work propperly. (Atleast i did not get it to work.)

Here is a simple file structure muckup:

**./Description.ext**
```cpp
class CfgFunctions {
    #include "stuff/unctions/CfgFunctions.hpp"
};
```

**./stuff/functions/CfgFunctions.hpp**
```cpp
class cScripts {
    class print {
        file = "stuff\functions\print";
        class helloWorld{};
    };
};
```

**./stuff/functions/print/fn_HelloWorld.sqf**
```cpp
#include "..\script_component.hpp"
/*
 * Author: CPL.Brostrom.A
 *  This function print debug information in the RPT log
 *
 * Arguments:
 * 0: Message <STRING>
 *
 * Example:
 * ["Something is wrong here."] call cScripts_fnc_HelloWorld
 * [formatText["%1 is a player.", player]] call cScripts_fnc_HelloWorld
 *
 */

params [
    ["_message","",[]],
    ["_topic","",[]],
    ["_showInChat",false,[false]]
];

private _prefix = formatText["[%1]", "TEST"];
private _type = "INFO";
if !(_topic == "") then {_topic = formatText[" (%1)", _topic]};

diag_log formatText ["%1%2 %3: %4", _prefix, _topic, _type, _message];

```

**./init.sqf**
```cpp
#include "script_component.hpp"
["Something is wrong here."] call FUNC(HelloWorld);
```

Here is hte repo i tried to get it to work on for the first place:
https://github.com/7Cav/cScripts

**Comment by HakonRydland** [comment]
so is the autocomplete not working at all or is the problem that header preview and peek not working when using the `FUNC()` macro?

**Comment by AndreasBrostrom** [comment]
i dont get anything
![image](https://user-images.githubusercontent.com/13811113/115744117-90832a80-a392-11eb-91f9-b3d91ad0eff5.png)

**Comment by HakonRydland** [comment]
ok for a quick fix on your end alter viewDistance cfg from
```sqf
class TAW_VD {
    tag = "TAWVD";
``` 
to
```sqf
class TAWVD {
```

a permanent fix my end can take some time due to irl stuff, thank you for the report

**Comment by HakonRydland** [comment]
New update released that resolves this issue.

as an additional note i also added a Tagless option so that the extension functionality will work with FUNC macros, be aware this can cause some trouble if you have multiple function with the same name and different tags. and macros are not being processed so it will not work with EFUNC macros
