### ISSUE TITLE
Going to a wiki entry of a BIS function ommits a dividing forward slash.

### ISSUE THREAD

**Issue by CalebSerafin** [HakonRydland/Arma3CfgFunctions#4]
## Problem
When using the `Go to wiki entry` feature on BIS functions, the forward slash between wiki and the function name is missing.

## Example
It goes to `https://community.bistudio.com/wikiBIS_fnc_dynamicText` instead of `https://community.bistudio.com/wiki/BIS_fnc_dynamicText`

**Comment by HakonRydland** [comment]
solved with new update
